Fix/changes in header to look similar to Main page of New Relic website
newrelic/instant-observability-website pull request #134
Opened 2022-04-05 11:43 UTC by sjyothi54

JIRA:https://newrelic.atlassian.net/browse/CXPUI-33
Description:The global header of I/O website had changed to look similar to the main page header of new relic website.
Screenshots Attached:
**OLD VIEW**
<img width="1433" alt="Screenshot 2022-04-05 at 5 05 16 PM" src="https://user-images.githubusercontent.com/99384747/161745587-9bed09a4-912f-4156-8834-970e84573237.png">
Mobile view:
<img width="376" alt="Screenshot 2022-04-05 at 5 05 51 PM" src="https://user-images.githubusercontent.com/99384747/161745657-8dff46a6-caf8-4c51-ac58-3da2382cd4b1.png">
**NEW VIEW**
<img width="1436" alt="Screenshot 2022-04-05 at 5 06 08 PM" src="https://user-images.githubusercontent.com/99384747/161745741-2d71721a-d982-4959-acc3-42a68b1dc3c5.png">
In dark mode:
<img width="1429" alt="Screenshot 2022-04-05 at 5 07 00 PM" src="https://user-images.githubusercontent.com/99384747/161746193-9e7a7376-1cf8-48d3-b837-929761f6316f.png">
MOBILE VIEW:
<img width="377" alt="Screenshot 2022-04-05 at 5 06 30 PM" src="https://user-images.githubusercontent.com/99384747/161746250-bed29258-7762-4a44-97d7-458b98b780f7.png">

<img width="373" alt="Screenshot 2022-04-05 at 5 06 42 PM" src="https://user-images.githubusercontent.com/99384747/161746284-1e6f15b4-7beb-4a20-b9b3-280543cd6f1f.png">

2022-04-06 06:02 UTC, sjyothi54 commented
Gatsby-build URL:https://build-ad54eb8f-319b-421b-a283-fd226137f925.gtsb.io/instant-observability/

2022-04-08 10:33 UTC, pkosanam requested changes
Here are my review comments:
1. On medium screen resolutions, I am able to see a scroll on the header. Please implement a button just like mobile view.
2. @aswanson-nr request you to kindly have a look at the line 54 if it is the write way to proceed
`const activePath = 'instant-observability';`
3. on line 220, kindly remove the extra space and format the code and maintain indentation

2022-04-12 20:33 UTC, aswanson-nr submitted a review, later dismissed
@sjyothi54 This looks fantastic!!! I had one comment, but it's definitely not a required change

2022-04-12 20:33 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +            id={href.includes(activePath) && 'header-nav-active-tab'}
Let me start by saying this totally works just fine! But something to think about, this header is only ever displayed when on `/instant-observability`, so this will always be the active tab. If you wanted to reduce complexity, you could just always make this active without checking the path.

2022-04-14 08:53 UTC, sjyothi54 commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +            id={href.includes(activePath) && 'header-nav-active-tab'}
@aswanson-nr Made necessary changes that you had mentioned it, kindly review it

2022-04-14 08:54 UTC, pkosanam approved these changes

2022-04-14 08:55 UTC, merged