chore: CXPUI 45 : Handle redirects for UR
newrelic/instant-observability-website pull request #136
Opened 2022-04-08 10:39 UTC by dikshab0202

JIRA: https://newrelic.atlassian.net/browse/CXPUI-45
Description: handle redirects for URLs when a quickstart name changes
Fix: added new redirect json file and

2022-04-08 12:44 UTC, pkosanam requested changes
Please make sure the indentation on quickstart-redirects.json file is right

Hi @aswanson-nr, request you to kindly review this PR as we have changed the URLs in "to" and "from" 
Thank you.

2022-04-12 20:35 UTC, aswanson-nr approved these changes
Tested the redirect and it works perfectly!

2022-04-12 20:40 UTC, aswanson-nr requested changes
Noticed one small thing we need to change!

2022-04-12 20:40 UTC, aswanson-nr commented on gatsby-node.js
> +      redirectInBrowser: true,
Let's remove this option, it makes Gatsby use meta redirects to change pages. Which can have a bad impact on SEO results. Just FYI, when working with non-browser redirects and Gatsby, the redirects will not work in development mode and PR previews. What happens is Gatsby Cloud picks up the generated `build/_redirects.json` file and uses that to do server side redirects, which only happens on production domains.
```suggestion
```

2022-04-13 07:44 UTC, dikshab0202 commented
> Noticed one small thing we need to change!

Hi @aswanson-nr , updated the commit suggestion in PR. Thank you..

2022-04-13 21:12 UTC, aswanson-nr approved these changes

2022-04-14 07:23 UTC, pkosanam approved these changes
looks good

2022-04-14 07:24 UTC, merged