Add new header for I/O site
newrelic/instant-observability-website pull request #14
Opened 2022-01-26 23:46 UTC by tabathadelane

Add a new GlobalHeader component for the I/O repo. 

<img width="1167" alt="Screen Shot 2022-01-26 at 3 33 02 PM" src="https://user-images.githubusercontent.com/47728020/151264635-fc8404ed-e585-4779-8a37-a14e9225afc9.png">

-A search icon now opens the `SearchModal`
-Removed border from `Login` button
-The dark mode icon moved to far right side of screen
-Changed the links on the nav tabs

The previews all varied slightly on a few things. I went with the screenshot in the ticket for this first iteration. 

Screenshot in the ticket:
![image](https://user-images.githubusercontent.com/1395158/149549165-4c621777-d1d7-4a49-a26d-d6ad9187c4cd.png)

If we are going with the tabs listed in this^ mockup, I will need some some URL suggestions. `Platform` & `Solutions` open dropdowns on `newrelic.com` and don't link to anything directly.

2022-01-26 23:48 UTC, tabathadelane commented on src/layouts/QuickStartLayout.js
> +import GlobalHeader from '../@newrelic/gatsby-theme-newrelic/GlobalHeader';
I'd like some input on if this is the correct way to do this. 😬

2022-01-27 17:10 UTC, tabathadelane commented
I am realized I need to change the colors for light mode. I thought that was just my desktop being in "Night Shift."

2022-01-31 18:27 UTC, tabathadelane commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +    href: 'https://developer.newrelic.com/instant-observability/',
This will need to updated eventually. Do it now? or later?

2022-01-31 18:55 UTC, josephgregoryii submitted a review, later dismissed
Assuming the comment above is noted for a later ticket, Looks awesome! I'm able to build and serve locally to see the updated header.

2022-01-31 21:21 UTC, aswanson-nr reviewed
Looks pretty much good to go to me!! Let's just update that link

2022-01-31 21:27 UTC, aswanson-nr submitted a review, later dismissed

2022-01-31 21:32 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +              <SplitTextButton
Let's get this back to using a regular button, since we aren't running the A/B test on this site!

2022-01-31 22:07 UTC, tabathadelane commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                // instrumentation={{
This was on the SplitTextButton component. I don't think we need this now, but wanted to confirm before I erased it.

2022-01-31 23:57 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                // instrumentation={{
yes! Let's keep it, it's used under the hood by the ExternalLink component to send tessen events on click!

2022-02-01 00:04 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                //   component: 'SplitTextButton',
@jpvajda Would you like us to change the component event name here? `SplitTextButton` is the current value from the dev/oss/docs sites, but this site is not using the split test button so it might be worth changing to something like `signUp`, but then it won't match up to the events coming from the  other sites

2022-02-01 18:21 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                //   component: 'SplitTextButton',
After further discussion, we are going to keep the `instrumentation` prop and update the component field to be `signUp`

2022-02-01 19:27 UTC, jpvajda requested changes

2022-02-01 19:27 UTC, jpvajda commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                //   component: 'SplitTextButton',
@aswanson-nr / @tabathadelane I'm thinking we should call this event `SignupButton` and also change the code in the theme for this [component](https://github.com/newrelic/gatsby-theme-newrelic/search?q=splittextbutton) to follow this naming convention.

I made a ticket for it, which I was going to take on. 🤠  let me know what you think

2022-02-01 19:27 UTC, jpvajda commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                //   component: 'SplitTextButton',
https://github.com/newrelic/gatsby-theme-newrelic/issues/633

2022-02-01 22:27 UTC, tabathadelane commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                  component: 'signUp',
```suggestion
                  component: 'SignupButton',
```

2022-02-01 22:59 UTC, aswanson-nr approved these changes

2022-02-01 22:59 UTC, merged