Chore:NR-1644-Landing pages-web- comprehensive monitoring section
newrelic/instant-observability-website pull request #140
Opened 2022-04-26 07:03 UTC by sjyothi54

JIRA:https://issues.newrelic.com/browse/NR-1644
Description:Update fonts/ colours in each of these sections of
Why monitor 
What should you look for in a .NET monitor 
What’s included in this quick start
What makes this unique
which looks similar to the figma design
NOTE: font-family will reflect only when the PR:https://github.com/newrelic/instant-observability-website/pull/137 got merged
Screenshots:
<img width="1283" alt="Screenshot 2022-04-25 at 8 27 06 PM" src="https://user-images.githubusercontent.com/99384747/165240144-426c0995-06d9-4e29-8f94-565a5a309af9.png">
<img width="1378" alt="Screenshot 2022-04-25 at 8 27 19 PM" src="https://user-images.githubusercontent.com/99384747/165240327-83392fd3-98c5-45f9-b833-1bcc6ee396f3.png">
Mobile view:
<img width="301" alt="Screenshot 2022-04-25 at 8 30 25 PM" src="https://user-images.githubusercontent.com/99384747/165240161-3272d97c-a2d2-450d-8890-732d3b02d896.png">

2022-04-26 18:33 UTC, aswanson-nr requested changes
Changes look good! I noticed some small styling differences compared to the figma design and called them out. I also noticed 2 files that we probably don't want to commit any changes to, `src/data/quickstarts.json` and `src/data/related-pages.json` both of these files are auto generated by workflows. So we could run into some interesting merge conflicts when we merge the feature branch back into `main`

2022-04-26 18:33 UTC, aswanson-nr commented on src/components/QuickstartOverview.js
>              h3 {
Looking at the preview, the H3s don't seem to have the same font-weight as the figma design. I'm not sure if that's because this doesn't have the new fonts yet, but just wanted to call that out.

2022-04-26 18:33 UTC, aswanson-nr commented on src/components/QuickstartOverview.js
>            css={css`
To avoid having to list the font color for each html tag, we could put the color up here and let it cascade to the other styles.
```suggestion
          css={css`
            color: #1d252c;
```

2022-04-26 18:33 UTC, aswanson-nr commented on src/data/quickstarts.json
>      ],
This file is auto generated by the `Fetch Quickstarts` workflow, please remove this before merging otherwise we could run into some tough conflicts when we merge this feature branch back into `main`

2022-04-27 07:20 UTC, sjyothi54 commented
@AlecIsaacson I am closing this PR because even i am reverting the changes of related-pages.json it is not reflecting here
So i raised new PR:https://github.com/newrelic/instant-observability-website/pull/143 regarding this issue.

2022-04-27 07:20 UTC, closed without merging