chore : NR1642 - whats included -Dashboards, Alerts & DataSources section
newrelic/instant-observability-website pull request #141
Opened 2022-04-26 07:27 UTC by dikshab0202

JIRA : https://issues.newrelic.com/browse/NR-1641
Description: created 3 separate new components for each section and 4 components for 4 new icons.

<img width="1124" alt="Screenshot 2022-04-26 at 12 54 19 PM" src="https://user-images.githubusercontent.com/101187392/165245149-f20b1494-ee59-4495-9521-4d5e04c51937.png">

<img width="1124" alt="Screenshot 2022-04-26 at 12 54 33 PM" src="https://user-images.githubusercontent.com/101187392/165245154-b5f4a6b8-b530-4121-b9ab-02487fa37ff6.png">

<img width="1124" alt="Screenshot 2022-04-26 at 12 54 54 PM" src="https://user-images.githubusercontent.com/101187392/165245162-e2bb05e9-2e4d-4374-92b9-44340decbd3c.png">

<img width="1680" alt="Screenshot 2022-04-26 at 12 55 31 PM" src="https://user-images.githubusercontent.com/101187392/165245167-b0ad1ed8-3e19-4d9f-a77b-9ad65e41eefb.png">

<img width="1680" alt="Screenshot 2022-04-26 at 12 55 47 PM" src="https://user-images.githubusercontent.com/101187392/165245172-beceda19-6b9d-4e3f-8967-42b10373b9de.png">

2022-04-26 18:46 UTC, aswanson-nr requested changes
Overall looks fantastic! Just noticed some odd behavior in a few spots, I attached some screenshots to help with debugging.
<img width="1857" alt="Screen Shot 2022-04-26 at 11 35 36 AM" src="https://user-images.githubusercontent.com/70179303/165370490-d7cdd71d-e83c-47b4-aa96-186eb2479e71.png">

2022-04-26 18:46 UTC, aswanson-nr commented on src/components/QuickstartDashboards.js
> +          <Slider {...settings}>
I noticed you're using a slider here, but in the preview it does not appear to be displaying them as a slider.
<img width="1915" alt="Screen Shot 2022-04-26 at 11 41 01 AM" src="https://user-images.githubusercontent.com/70179303/165369822-a3f2d290-8da5-48d9-a24c-b14128e86795.png">

2022-04-26 18:46 UTC, aswanson-nr commented on src/components/WhatsIncluded/Dashboards.js
> +                    </p>
The other `WhatsIncluded` components use the `EmptyState` component for this case. I think either is fine, but we should be consistent across these components.

2022-04-27 09:43 UTC, dikshab0202 commented on src/components/QuickstartDashboards.js
> +          <Slider {...settings}>
Hi Alec, it is resolved. Can you please review once again?

2022-04-27 09:44 UTC, dikshab0202 commented on src/components/WhatsIncluded/Dashboards.js
> +                    </p>
Replaced this code.

2022-04-27 22:41 UTC, aswanson-nr approved these changes

2022-04-28 03:41 UTC, merged