Feat/nr1509
newrelic/instant-observability-website pull request #145
Opened 2022-04-28 00:49 UTC by tabathadelane

UI updates for the Categories `aside` and  mobile `Overlay` elements.

Relates to [NR-1509](https://issues.newrelic.com/browse/NR-1509)

<img width="1123" alt="Screen Shot 2022-04-27 at 5 44 38 PM" src="https://user-images.githubusercontent.com/47728020/165654315-2ebb6c95-8169-4de5-9804-06689a742db2.png">
<img width="242" alt="Screen Shot 2022-04-27 at 5 44 09 PM" src="https://user-images.githubusercontent.com/47728020/165654326-d5ee1fd0-93d4-4a31-8356-d58291f888a1.png">
<img width="242" alt="Screen Shot 2022-04-27 at 5 44 00 PM" src="https://user-images.githubusercontent.com/47728020/165654330-3aec764f-7722-403c-8b5d-15b5b0d49a75.png">

2022-04-28 22:18 UTC, aswanson-nr requested changes
Overall looks great! Just noticed one problem with button colors.

2022-04-28 22:18 UTC, aswanson-nr commented on src/pages/index.jsx
> +                      background: #1a3c34;
Noticed that the `cancel` button hover color is still teal, could you update that here?

2022-04-28 22:43 UTC, tabathadelane commented on src/pages/index.jsx
> +                      background: #1a3c34;
Nice catch. Done!

2022-04-29 18:38 UTC, aswanson-nr approved these changes

2022-04-29 18:43 UTC, aswanson-nr approved these changes

2022-04-29 18:43 UTC, merged