New footer (rebrand) - NR1515
newrelic/instant-observability-website pull request #148
Opened 2022-04-29 21:49 UTC by josephgregoryii

Updates to new global footer component

2022-04-29 23:57 UTC, tabathadelane requested changes
Looking super. Left some feedback/questions.

2022-04-29 23:57 UTC, tabathadelane commented on src/layouts/QuickStartLayout.js
> +import '../components/fonts.scss';
Oops. I think these are imported twice.

2022-04-29 23:57 UTC, tabathadelane commented on src/layouts/QuickStartLayout.js
> +          }
Why 920? I think the rest of the site switches to mobile at 760px.

2022-04-29 23:57 UTC, tabathadelane commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +const RESOURCES = [
Should we import these instead of adding 90 lines to this file?

2022-04-29 23:57 UTC, tabathadelane commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +        font-feature-settings: 'ss02' on;
I can't figure out what this does. I didn't use it in my branches 🙈

2022-04-29 23:57 UTC, tabathadelane commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +            {SOCIALS.map((social) => (
These turn to the white svgs on hover in the figma

2022-04-29 23:57 UTC, tabathadelane commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +          text-decoration: underline;
There are no hover styles for this in the figma. I like it, but don't know if its necessary since the user does get the pointer style change to indicate it is a link.

2022-04-30 00:06 UTC, josephgregoryii commented on src/layouts/QuickStartLayout.js
> +          }
By design, the footer in the desktop version is quite wide. If it doesn't break until 760px, it gets quite funky. I'm happy to through this on Monday if you have other ideas!

2022-04-30 00:10 UTC, josephgregoryii commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +        font-feature-settings: 'ss02' on;
Tbh, i dont think it does anything 🙈 . Consider it removed 👍🏻

2022-04-30 00:11 UTC, josephgregoryii commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +            {SOCIALS.map((social) => (
Good catch, i didn't see if there were any hover styling

2022-04-30 00:18 UTC, josephgregoryii commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +          text-decoration: underline;
Good call - I wasnt sure about it and this makes sense. Follow up: should it turn white as well to be consistent with how the SVGs for the socials turn white?

2022-04-30 00:37 UTC, josephgregoryii commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +const RESOURCES = [
done!

2022-04-30 00:37 UTC, josephgregoryii commented on src/layouts/QuickStartLayout.js
> +import '../components/fonts.scss';
fixed

2022-05-02 17:49 UTC, tabathadelane approved these changes
⭐

2022-05-02 18:08 UTC, merged