NR-5626: Landing banner screenshot size inconsistencies
newrelic/instant-observability-website pull request #170
Opened 2022-05-10 20:07 UTC by tabathadelane

- The banner now checks if there is a dashboard screenshot that fits in the desired aspect ratio for the design (near 16:9)
- if it doesn't have one, use the default image
- the provided default image is NOT the correct aspect ratio, so padding will be added if that image is chosen for display.

- This only loops over the first dashboard's screenshots to avoid nested loops, but that can be easily added if we want to be that motivate to find a screenshot 
- The aspect ratio range can also easily be changed depending on how varied we want the images to be displayed in the banner design. Since these are screenshots taken from parts of a users dashboard, the likelihood if it being exactly 16:9 (1.77777777778) is very low. This currently looks for images between 2 and 1.5 aspect ratio.

### Cloudflare does not have any screenshots that fit the aspect ratio range
<img width="1863" alt="Screen Shot 2022-05-10 at 1 05 44 PM" src="https://user-images.githubusercontent.com/47728020/167712828-88545b08-dd83-420f-b600-131e6c7622cb.png">

### Node.js does have an image within the desired aspect ratio (~1.9)
<img width="1866" alt="Screen Shot 2022-05-10 at 12 16 44 PM" src="https://user-images.githubusercontent.com/47728020/167712053-dfc462a2-8df5-444c-bb32-0a2eebe10128.png">

2022-05-10 23:31 UTC, aswanson-nr requested changes
This works so well!!! Just noticed a few small things to clean up, but then it should be good to go!

2022-05-10 23:31 UTC, aswanson-nr commented on src/components/GetStartedFooter.js
> +            }
I'm pretty sure @zstix handled this in #163, merging in the feature branch should take take of that.

2022-05-10 23:31 UTC, aswanson-nr commented on src/components/GetStartedFooter.js
> +            }
Same with this one

2022-05-10 23:31 UTC, aswanson-nr commented on src/components/LandingBanner/index.js
> +    for (const screenshot of quickstart.dashboards[0].screenshots) {
I'm curious what kind of behavior this will have for quickstarts that don't have any dashboards, we might need to check for that first.

2022-05-10 23:31 UTC, aswanson-nr commented on src/components/QuickstartDashboards.js
> +                <div
I think these changes might just be appearing because this was branched off an older version, getting the latest feature branch should remove them

2022-05-10 23:31 UTC, aswanson-nr commented on src/components/WhatsIncluded/Dashboards.js
> +            margin: 0px 0px;
I think these also have to do with an older version of the feature branch, should be handled after an update.

2022-05-10 23:55 UTC, tabathadelane commented on src/components/LandingBanner/index.js
> +    for (const screenshot of quickstart.dashboards[0].screenshots) {
good catch! updated.

2022-05-11 15:57 UTC, aswanson-nr requested changes
This looks ready to go! Just need to remove a console.log

2022-05-11 15:57 UTC, aswanson-nr commented on src/components/LandingBanner/index.js
> +        console.log('new image', image);
```suggestion
```

2022-05-11 17:32 UTC, aswanson-nr requested changes
Looks like we just want to get the default image into the correct aspect ratio before merging!

2022-05-11 17:32 UTC, aswanson-nr commented on src/components/LandingBanner/index.js
> +    style: { padding: ' 20px 100px 0' },
Let's edit the image to make it the correct aspect ratio, instead of having to deal with extra styling here.

2022-05-11 20:40 UTC, aswanson-nr approved these changes

2022-05-11 20:40 UTC, merged