NR-4041: Parse quickstart PR files
newrelic/instant-observability-website pull request #192
Opened 2022-05-17 16:45 UTC by tabathadelane

parses the raw files from the github API and shapes them to match what the `QuickstartDetails.js` expects

`http://localhost:8000/preview?pr=1090&quickstart=golden-signals-web` is a good url to use to look at both dashboard and alert content

2022-05-17 17:34 UTC, josephgregoryii reviewed
This looks great! just a couple comments

2022-05-17 17:34 UTC, josephgregoryii commented on src/hooks/usePullRequestQuickstart.js
> +  const [contentFiles, setContentFiles] = useState([]);
```suggestion
  const [quickstart, setQuickstart] = useState({});
```
Since the hook has parsing now, we might want to change this to hold the state of the parsed quickstart instead since we don't need to worry about the files anymore.

2022-05-17 17:34 UTC, josephgregoryii commented on src/hooks/usePullRequestQuickstart.js
> +    };
We changed up how this function error handles. We add a try catch to handle that here:

https://github.com/newrelic/instant-observability-website/blob/962b6a8a3a8ccf47450819d95088c52801199f23/src/pages/preview.jsx#L38-L48

2022-05-17 17:34 UTC, josephgregoryii commented on src/hooks/usePullRequestQuickstart.js
> +    };
So we just need a try/catch here :)

2022-05-17 17:34 UTC, josephgregoryii commented on src/utils/preview/parseHelpers.js
> +    const trimmedDocumentation = loadYaml.documentation.map((doc) => {
`documentation` is an optional parameter and breaks on quickstarts that do not have a `documentation` field in their config file.

example: `http://localhost:8000/preview?pr=1060&quickstart=battlesnake`

2022-05-17 17:34 UTC, josephgregoryii commented on src/utils/preview/parseHelpers.js
> +export const parseQuickstartFilesFromPR = async (rawFileContent) => {
I dont think we need async here, but i might be missing something!

2022-05-17 17:57 UTC, josephgregoryii commented on src/utils/preview/parseHelpers.js
> +};
Sorry! One last comment - I think I/O wants dashboards to be an array of objects.

example:
```
{
...,
dashboards: [
      {
        "name": "Battlesnake Performance",
        "description": "Monitor your Battlensakes performance and see how it stacks up against your competition!",
        "url": null,
        "screenshots": [
          "https://raw.githubusercontent.com/newrelic/newrelic-quickstarts/main/quickstarts/battlesnake/dashboards/battlesnake-performance/battlesnake-performance.png"
        ]
      },
    ...
  ]
}

```

2022-05-17 18:04 UTC, tabathadelane commented on src/utils/preview/parseHelpers.js
> +};
i am trying to take care of that on line 99

`dashboardDirs = Object.values(dashboardDirs);`

but it's not running before its returning the quickstart 🥴

2022-05-17 18:10 UTC, aswanson-nr reviewed
I left a few comments around the globally scoped variables for the quickstart. I think we'll want to pull that scope out of global. Seems like a great opportunity to pair up and reword that part.

2022-05-17 18:10 UTC, aswanson-nr commented on src/utils/preview/parseHelpers.js
> +};
These variables are sitting in the global scope, let's get them moved into a function so that they are only scoped to that function and its return value. That will most likely require some changes to each function, I'll leave comments on each one.

2022-05-17 18:10 UTC, aswanson-nr commented on src/utils/preview/parseHelpers.js
> +const checkFileType = (rawFile) => {
This function name is a little misleading, it does check the file type, but it also parses the file as well. Since we're not exporting it, we can keep the name simple, maybe something like this:
```suggestion
const parseFiles = (rawFile) => {
```

2022-05-17 18:10 UTC, aswanson-nr commented on src/utils/preview/parseHelpers.js
> +};
To remove the use of global variables, each of the parse functions could return their part of the quickstart object and then this function could handle stitching that together and returning it.

2022-05-17 18:10 UTC, aswanson-nr commented on src/utils/preview/parseHelpers.js
> +    const file = rawFile[each];
If you use a `for of` here, line 78 shouldn't be needed.
```suggestion
  for (const file of rawFile) {
```

2022-05-17 23:20 UTC, josephgregoryii requested changes
Code looks great! - Requesting changes as a placeholder to reference adding tests to this PR

2022-05-19 22:06 UTC, zstix commented on src/utils/preview/parseHelpers.js
> +
```suggestion
```

2022-05-19 22:09 UTC, zstix commented on src/hooks/usePullRequestQuickstart.js
> +        const parsedQuickstart = await parseQuickstartFilesFromPR(
This doesn't need to be async.

```suggestion
        const parsedQuickstart = parseQuickstartFilesFromPR(
```

2022-05-19 22:11 UTC, zstix commented on src/utils/preview/parseHelpers.js
> +const parseFiles = (rawFile) => {
We probably want to name this argument `rawFiles` (note the plural) since this is supposed to be an array of files.

A docstring (or types) would really help here too. I'm not sure from looking at this if it's a file path, file content, or a buffer.

2022-05-19 22:18 UTC, zstix commented on src/utils/preview/parseHelpers.js
> +  return parsedQuickstart;
Super minor, but we probably don't need to define a variable if we're just going to return it.

```suggestion
  return { ...quickstartDirs, ...quickstart };
```

2022-05-19 22:23 UTC, zstix commented on src/utils/preview/parseHelpers.js
> +  return alerts;
Rather than making an empty array, looping over the array, pushing a modification into the empty array, and returning it, we could use [`Array.prototype.map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) to simplify this:

```suggestion
  return alertFiles.forEach((file) => {
    const loadYaml = yaml.load(file.content);

    return {
      details: loadYaml.description?.trim() ?? '',
      name: loadYaml.name?.trim() ?? '',
      type: loadYaml.type?.trim() ?? '',
    };
  });
```

2022-05-19 22:36 UTC, zstix commented on src/utils/preview/parseHelpers.js
> +    }
I wonder if it would be simpler to get all the dashboard sub-directories first, and then loop through each to get the files. That way we don't need to work with an object or check if the key exists. Here's a rough sketch:

```js
// not sure if there's a built-in function from `fs` to get all subdirectories...
return getSubdirectories(dashboardFiles).map((directory) => {
  // find JSON file in directory
  // get name and description from JSON file
  // find all image files in directory
  return { name, description, screenshots };
});
```

That should produce the same results with a little less custom code. Totally a style choice tho. Your call.

2022-05-19 22:45 UTC, zstix commented on src/utils/preview/parseHelpers.js
> +  });
This could probably be simplified to use [`Array.prototype.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) here:

```js
  const config = quickstartFiles.find((file) => {
    return file.type === 'yaml' && file.fileName.includes('config');
  });
```

It could be further simplified to use [`path.basename`](https://nodejs.org/docs/latest-v17.x/api/path.html#pathbasenamepath-ext):

```js
  const config = quickstartFiles.find((file) => {
    return path.basename(file) === 'config.yml';
  });

2022-05-20 19:55 UTC, aswanson-nr commented on src/utils/__tests__/parseHelpers.test.js
> +describe('Action: Parse helpers', () => {
I think the `Action:` part here was only used for tests that relate to Github actions, so let's just name it after the file it's testing.
```suggestion
describe('parseHelpers', () => {
```

2022-05-20 19:59 UTC, aswanson-nr approved these changes

2022-05-20 20:02 UTC, merged