chore: removed build your own tile
newrelic/instant-observability-website pull request #20
Opened 2022-02-04 21:37 UTC by jpvajda

This PR removes the build your own tile and replaces the create issue button with build your own.

2022-02-04 23:36 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +            as={Link}
Looks like this button is trying to do a relative link for some reason. I think this might need to be an `ExternalLink`
```suggestion
            as={ExternalLink}
```

2022-02-07 20:07 UTC, jpvajda commented
@aswanson-nr I tried changing to ExternalLink and the URL is still pointing to the I/O domain an not to the external link provided.

2022-02-07 21:17 UTC, zstix commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
> +            to="https://developer.newrelic.com/contribute-to-quickstarts/"
According to [the docs](https://github.com/newrelic/gatsby-theme-newrelic/tree/main/packages/gatsby-theme-newrelic#externallink), I think we want to use `href` not `to`. Let's see if that solves the problem 🤷 
```suggestion
            href="https://developer.newrelic.com/contribute-to-quickstarts/"
```

2022-02-07 22:39 UTC, jpvajda commented
@zstix thanks for that suggestion! I did make that change, and still no luck. 🤔

2022-02-08 00:01 UTC, aswanson-nr requested changes
The reason this link isn't working as intended is due to [this line](https://github.com/newrelic/gatsby-theme-newrelic/blob/ef77172fcd611007367769a52fe6872dda09bf4d/packages/gatsby-theme-newrelic/src/components/Link.js#L63-L68) in our `Link` component. The reason this is happening on this site is that our [site metadata](https://github.com/newrelic/instant-observability-website/blob/main/gatsby-config.js#L18) config in `gatsby-config.js` is still set to the developer site

2022-02-08 00:13 UTC, jpvajda commented
@aswanson-nr pointed to the need for the sitemeta data to be updated for the new domain, so I made that change and the external link now works 💯

2022-02-08 00:24 UTC, josephgregoryii commented on src/pages/index.jsx
> -            />
Are we going to bring back the Quickstart tile at a later point?

2022-02-08 00:25 UTC, josephgregoryii approved these changes
👍🏻  with a discussion comment about `QuickstartTile`

2022-02-08 00:25 UTC, josephgregoryii commented on src/pages/index.jsx
> -            />
If not, we should consider removing the file 😄

2022-02-08 16:14 UTC, jpvajda commented
@josephgregoryii I think we can leave it for now, as we are handing off this site to another team soon and it's possible they may want to be bring back the individual tile for building your own.

2022-02-08 17:38 UTC, aswanson-nr commented on src/pages/index.jsx
> -            />
The `QuickstartTile` component is used for all quickstarts! So this is all that needs to be done

2022-02-08 17:38 UTC, merged

2022-02-08 23:29 UTC, jpvajda commented
one closing comment, we did end up removing all the code for build your own, but it can be resurrected in git history if it's needed again.