NR-12569 :  header section in mobile and web view
newrelic/instant-observability-website pull request #212
Opened 2022-05-24 06:26 UTC by dikshab0202

JIRA : https://issues.newrelic.com/browse/NR-11585
subtask: https://issues.newrelic.com/browse/NR-12569
Description: 
1. Header is sticky in web view and non-sticky in mobile view
2. z-index=0 applied for header  bottom border line in mobile view
3. new relic logo size lesser in mobile view than web view
4. adjusted font-size and height
5. hover color is now same.

After change
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101187392/169962980-ad88f737-9fb9-4267-adb2-7c065b3fd534.png">

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/101187392/169963192-003bb128-01f4-401d-a4ed-055068a1c430.png">

2022-05-24 10:07 UTC, dikshab0202 commented
> Please sync this branch with the main branch. I have seen that the main branch got updated with a fix which I do not see in this branch. Thank you.

@pkosanam , okay , it is done.

2022-05-24 11:17 UTC, pkosanam commented
Observed these things to be fixed:
1. On header, "login" and "Get started" should have styles on hover
2. Focus styles on the header are not similar to newrelic.com

2022-05-25 02:04 UTC, dikshab0202 commented
> Observed these things to be fixed:
> 
> 1. On header, "login" and "Get started" should have styles on hover
> 2. Focus styles on the header are not similar to newrelic.com

Hi @pkosanam , worked on above points, please review and let me know if any suggestions.

2022-05-25 07:26 UTC, pkosanam commented
Observed things which has to be fixed
1. color of the menu options are not same as newrelic.com
2. Login and Get started are moving when hovered

3. Styles when focused(on links and also on the buttons on mobile view) are not matching as per newrelic.com
<img width="424" alt="image" src="https://user-images.githubusercontent.com/99316285/170204757-ae1ebbaf-3457-4e0e-a9d9-ec7ca14f15d6.png">

4. button on the carousel is hidden behind the card
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99316285/170204334-d3222a29-07da-45a8-8f85-d1b64bea7485.png">

2022-05-26 15:58 UTC, pkosanam requested changes

2022-05-26 15:58 UTC, pkosanam commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +            padding: 0 3.75rem;
I see that --site-content-padding has 3.75rem so you can use the below instead
padding: 0 var(--site-content-padding);

2022-05-26 15:59 UTC, pkosanam commented
On 1127px, mobile menu is not displayed
<img width="742" alt="image" src="https://user-images.githubusercontent.com/99316285/170526873-31ee9ab2-6967-4a87-9c0d-6c7566e5346b.png">

2022-05-27 06:48 UTC, dikshab0202 commented
> On 1127px, mobile menu is not displayed <img alt="image" width="742" src="https://user-images.githubusercontent.com/99316285/170526873-31ee9ab2-6967-4a87-9c0d-6c7566e5346b.png">

Hi @pkosanam , it is fixed now.

2022-05-27 08:15 UTC, pkosanam requested changes
application is working fine, please make these code changes

2022-05-27 08:15 UTC, pkosanam commented on src/components/styles.scss
> +  --global-header-height: 4rem !important;
cross check if height is changed on responsive screens

2022-05-27 08:50 UTC, dikshab0202 commented on src/components/styles.scss
> +  --global-header-height: 4rem !important;
this height is only applicable for toggle screen( responsive) according to code structure.

2022-05-27 08:51 UTC, dikshab0202 commented on src/pages/index.jsx
> -              </button>,
okay. done

2022-05-27 08:52 UTC, dikshab0202 commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +              justify-content: space-between;
okay. done.

2022-05-27 09:50 UTC, dikshab0202 commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                width: 10.625rem;
This is the logo width size breakpoint.

2022-05-27 09:52 UTC, dikshab0202 commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +            }
This one is the breakpoint when we can see toggle - 1127px

2022-05-27 10:13 UTC, merged