NR-18828: For smooth animations on buttons
newrelic/instant-observability-website pull request #233
Opened 2022-05-31 10:28 UTC by dikshab0202

JIRA : https://issues.newrelic.com/browse/NR-18828
Description: css fix for smooth animations

1. worked mainly on 'animatedText.js' component for the task
2. 'InstallButton.js' and 'LandingPageFooter.js'  , touched both files for respective buttons to maintain height and width
3. 'GetstartedFooter.js' -> observe height is 8px more than newrelic.com, so modified height.

2022-06-03 14:27 UTC, pkosanam approved these changes
Looks good.

In the upcoming versions, try creating a component named "Animated Button", just like "AnimatedText" and use it where ever required. 😃

2022-06-03 14:32 UTC, pkosanam requested changes
Please resolve conflicts

2022-06-03 16:55 UTC, dikshab0202 commented
> Please resolve conflicts

Hi @pkosanam , conflicts has been resolved.

2022-06-05 15:38 UTC, pkosanam approved these changes

2022-06-05 15:38 UTC, merged