NR-18359 : social sharing buttons and functionality in web and mobile…
newrelic/instant-observability-website pull request #240
Opened 2022-06-02 05:43 UTC by dikshab0202

JIRA: https://issues.newrelic.com/browse/NR-18359
Description: social media sharing buttons

1. style.scss -> added margin for buttons and formatted it
2. SVG.js -> 4 SVG files added for facebook, twitter, mail and linkedin
3. Dashboard.js -> added html and css for sharing buttons
4. package.json -> added react-share
5. Share.jsx -> new component for sharing buttons

Before changes
*******
<img width="268" alt="image" src="https://user-images.githubusercontent.com/101187392/171560712-42ee03af-5ff6-4ec5-ad15-4dc99b281629.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/101187392/171560806-e9687ef2-7612-415c-aca1-6db64d43a452.png">

After changes
********
<img width="269" alt="image" src="https://user-images.githubusercontent.com/101187392/171560535-9e6a9bcb-434b-459f-9095-de5500898bcb.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101187392/171560620-836b5659-a5cc-4c52-bdc2-856e69fc1d75.png">

2022-06-02 06:23 UTC, pkosanam requested changes

2022-06-02 06:23 UTC, pkosanam commented on src/components/WhatsIncluded/Dashboards.js
> +            <Share url={window.location.href} />
Instead of using "window.location.href" try using the below

import { useLocation } from "@reach/router"
const location = useLocation();
<Share url={location.href} />

2022-06-02 07:21 UTC, dikshab0202 commented on src/components/WhatsIncluded/Dashboards.js
> +            <Share url={window.location.href} />
modified.

2022-06-02 10:40 UTC, pkosanam requested changes
Kindly look into the requested changes

2022-06-02 10:40 UTC, pkosanam commented on src/components/Share.jsx
> +export default Share;
please add a new line after line 47 and format the document

2022-06-02 10:40 UTC, pkosanam commented on src/components/WhatsIncluded/Dashboards.js
> +        <div
This is what I have seen in very small screen.
Kindly fix this.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/99316285/171612042-bb01337d-194f-4221-a80f-786f094ba685.png">

2022-06-02 10:40 UTC, pkosanam commented on src/components/styles.scss
>  }
Please remove empty line 157 and a new line at the end of the page.
Kindly format the document too.

2022-06-02 13:35 UTC, dikshab0202 commented on src/components/WhatsIncluded/Dashboards.js
> +        <div
okay. Previously maintained 384px minimum width for responsiveness. Now responsiveness minimum width is 279px according to newrelic.com .

2022-06-02 13:37 UTC, dikshab0202 commented on src/components/styles.scss
>  }
Removed empty line and tried to give a new line at the end of the file, but after formatting, a new line is automatically removed for style.scss .

2022-06-03 04:50 UTC, pkosanam commented on src/components/styles.scss
>  }
ok

2022-06-03 12:06 UTC, pkosanam commented
closing this PR, as I have raised a new PR which is synced with main branch.
PR: https://github.com/newrelic/instant-observability-website/pull/242

2022-06-03 12:06 UTC, closed without merging