Download all logos at build time
newrelic/instant-observability-website pull request #256
Opened 2022-06-29 19:30 UTC by zstix

## Description
This makes use of `gatsby-source-filesystem` to download all _logos_ at build time and store them in a local cache. For images that are 
_not_ SVGs, they will be run through `gatsby-plugin-sharp` to be optimized for the right size and to be progressively loaded in. For 
images that _are_ SVGs, they will simply be downloaded and referenced.

This work includes a little bit of a refactor for the `QuickstartImg` component. Overall this file could use a little more cleanup, but 
I felt like that was a little outside of the scope of this ticket.

This work does _not_ include optimization of dashboard images. If we deem that necessary, we can do that work in a follow-up PR using 
this one as a starting point.

## Related Ticket(s)
- NR-20529

2022-06-29 20:15 UTC, aswanson-nr submitted a review, later dismissed
This looks so clean!!! I think we definitely want to do the work to pull in dashboard screenshots as well, we may get less gains on the performance side since they are only loading a few images per details page, but we get the confidence in knowing that the images are stored in the CDN with the rest of the site and changes to the quickstart repo can't affect the live site.

2022-07-01 21:02 UTC, zstix commented on plugins/gatsby-source-quickstarts/gatsby-node.js
> + * @todo Verify that `relatedResources` gets properly added from theme.
```suggestion
```

2022-07-05 18:16 UTC, zstix commented on plugins/gatsby-source-quickstarts/gatsby-node.js
> +
```suggestion
```

2022-07-05 18:35 UTC, zstix commented on src/pages/index.jsx
> +              height: 45
TODO: add a comment calling out why we have `45`(px) as a hard-coded value.

2022-07-05 19:03 UTC, zstix commented on src/templates/QuickstartDetails.js
> +              height: 280
This is really compromising the quality of the screenshots. Let's let CSS size the image and bring them in at full size. WEBP is still going to give us some filesize improvements (~50%)
```suggestion
```

2022-07-05 19:05 UTC, zstix commented on src/components/QuickstartDashboards.js
> +                        href={node.publicURL}
It looks like this `href` is not getting set. It's possible we might not have `publicURL`.

2022-07-05 19:05 UTC, zstix commented on src/templates/QuickstartDetails.js
> +          childImageSharp {
```suggestion
        screenshots {
          publidURL
          childImageSharp {
```

2022-07-05 20:29 UTC, mickeyryan42 submitted a review, later dismissed
Reviewed from a purely code perspective since I'm not super knowledgeable with the Gatsby side.  Looks awesome!

2022-07-05 20:54 UTC, aswanson-nr requested changes
Looking pretty much good to go to me! Images now link out to the original in a new tab.
The one issue I noticed is that the dashboard images are being loaded as full width while maintaining their height, see the attached screenshot.

### Live site
<img width="1376" alt="Screen Shot 2022-07-05 at 1 55 30 PM" src="https://user-images.githubusercontent.com/70179303/177414936-0fa74f02-ed7b-4ade-8c04-ff4fa6e15e7e.png">

### PR preview of this pull request
<img width="1282" alt="Screen Shot 2022-07-05 at 1 52 31 PM" src="https://user-images.githubusercontent.com/70179303/177414548-e935c90a-c71c-4556-b409-bd6579f3b885.png">

2022-07-05 21:46 UTC, aswanson-nr approved these changes

2022-07-05 21:57 UTC, merged