Build your own button is moved to left panel
newrelic/instant-observability-website pull request #26
Opened 2022-02-11 10:58 UTC by pkosanam

Applied "Build your own" button on the left panel.

OLD:
![image](https://user-images.githubusercontent.com/99316285/153579969-002425ae-2bad-4c1e-aea2-c3270933aadb.png)

NEW:
![image](https://user-images.githubusercontent.com/99316285/153579994-815dea4f-5965-46f9-b0cd-b5c00453bed5.png)

2022-02-11 10:58 UTC, pkosanam commented
JIRA Ticket ID: https://newrelic.atlassian.net/browse/CXPUI-5

2022-02-17 22:08 UTC, aswanson-nr commented
Looks like the CI/CD stalled out for this PR, I'm going to close and open it to kick them off again. @pkosanam Just FYI!

2022-02-17 22:34 UTC, aswanson-nr requested changes
Hey @pkosanam! I had a suggestion for an easier way to handle that link and a small comment on the wording.

2022-02-17 22:34 UTC, aswanson-nr commented on src/pages/index.jsx
> +                </Button>
Our theme actually provides a great way to handle linking and opening in a new tab via the button component. 
The `as` prop allows you to turn into into an external link, docs [here](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#button). **Note**: You'll need to import `ExternalLink` from the `@newrelic/gatsby-theme-newrelic` package.
So, we can do something like this:
```suggestion
                <Button
                  type="button"
                  key={RESERVED_QUICKSTART_IDS.BUILD_YOUR_OWN_QUICKSTART}
                  variant={Button.VARIANT.PRIMARY}
                  as={ExternalLink}
                  to={QUICKSTARTS_REPO}
                  instrumentation={{
                    component: 'SideNav',
                    eventName: 'instantObservability',
                    category: 'BuildYourOwnQuickstartClick',
                  }}
                >
                  Build your own
                </Button>
```
This allows you to avoid having to `window.open` and keeps the link accessible. I also added in the `instrumentation` prop, that helps our analytics tracking identify events.

2022-02-17 22:34 UTC, aswanson-nr commented on src/pages/index.jsx
> +              <Label htmlFor="quickstartCategory">Can build QuickStart</Label>
`Can build QuickStart` has product writing approved this wording? The general guidance has been to not capitalize the `S` and `Q` unless it's the start of a sentence, like `Quickstart` or `quickstart`. /cc @jpvajda

2022-02-18 08:13 UTC, pkosanam commented on src/pages/index.jsx
> +                </Button>
Thank you very much @aswanson-nr for your suggestions.
After discussing with the team, I was told to close this PR as there is no such requirement now.
Hence I am closing this PR.

2022-02-18 08:13 UTC, pkosanam commented
Thank you very much @aswanson-nr for your suggestions.
After discussing with the team, I was told to close this PR as there is no such requirement now.
Hence I am closing this PR.

2022-02-18 08:13 UTC, closed without merging