NR-21603: Keep search param on clicking category
newrelic/instant-observability-website pull request #261
Opened 2022-07-05 20:18 UTC by mickeyryan42

https://issues.newrelic.com/browse/NR-21603

2022-07-07 17:19 UTC, zstix approved these changes

2022-07-07 20:28 UTC, aswanson-nr requested changes
I noticed a bug where you can no longer clear the search bar.

1. search for "python"
2. select the "Application monitoring" category
3. clear the search term
4. search for "python"
5. clear the search term
Notice that you can no longer clear it, not quite sure what's going here.

2022-07-07 21:37 UTC, mickeyryan42 commented
> I noticed a bug where you can no longer clear the search bar.
> 
> 1. search for "python"
> 2. select the "Application monitoring" category
> 3. clear the search term
> 4. search for "python"
> 5. clear the search term
>    Notice that you can no longer clear it, not quite sure what's going here.

I can't seem to reproduce it, I'm wondering if I'm not seeing it because of the gatsby error message that pops up in dev.  Lets sync on it tomorrow!

2022-07-08 16:35 UTC, zstix approved these changes

2022-07-08 16:44 UTC, aswanson-nr approved these changes

2022-07-08 16:45 UTC, merged