Datasources to Documentation
newrelic/instant-observability-website pull request #300
Opened 2022-08-01 22:00 UTC by josephgregoryii

2022-08-01 22:12 UTC, tabathadelane submitted a review, later dismissed

2022-08-02 18:16 UTC, aswanson-nr requested changes
Looks like the empty state still uses the "data source" wording 
<img width="1151" alt="Screen Shot 2022-08-02 at 11 16 09 AM" src="https://user-images.githubusercontent.com/70179303/182445389-b0651f9f-757e-40d6-82f0-4fd00fb30761.png">
I used the `atlassian-jira` quickstart to test

2022-08-03 16:37 UTC, tabathadelane approved these changes

2022-08-03 17:11 UTC, aswanson-nr approved these changes

2022-08-15 15:43 UTC, merged