Updated new quickstarts titles and description.
newrelic/instant-observability-website pull request #334
Opened 2022-09-15 09:59 UTC by pkudikyala

**Ticket URL's:** 
1. https://issues.newrelic.com/browse/NR-31187,
2. https://issues.newrelic.com/browse/NR-31202,
3. https://issues.newrelic.com/browse/NR-30929

**Description:** 
Updated new quickstarts (Ansible tower, C# and Typescript) titles and descriptions in the metadata file.

2022-09-15 10:32 UTC, pkosanam requested changes

2022-09-15 10:32 UTC, pkosanam commented on src/data/quickstart-metadata.json
> +    "csharp": {
please change the slug name to "c-sharp"

2022-09-15 17:05 UTC, pkosanam requested changes

2022-09-15 17:05 UTC, pkosanam commented on src/data/quickstart-metadata.json
> +  "python": {
@pkudikyala, please check your line indentation

2022-09-16 09:15 UTC, pkudikyala commented on src/data/quickstart-metadata.json
> +  "python": {
Resolved line indentation and pushed

2022-09-19 16:05 UTC, aswanson-nr approved these changes

2022-09-19 16:07 UTC, zstix approved these changes

2022-09-19 16:07 UTC, aswanson-nr commented
Hey @pkosanam, it just needs you to approve the changes then github will let us merge!

2022-09-19 16:09 UTC, merged