chore: repo-linter-checks
newrelic/instant-observability-website pull request #53
Opened 2022-03-01 23:52 UTC by jpvajda

- This PR resolve the issues reported by repo-linter for OSS policies
- I also made markdown linter fixes

2022-03-02 17:39 UTC, zstix commented on README.md
> +[![Community header](https://github.com/newrelic/opensource-website/raw/master/src/images/categories/Community_Project.png)](https://opensource.newrelic.com/oss-category/#community-project)
This is an issue with how repolinter is handling these image paths.

2022-03-03 00:02 UTC, jpvajda commented on README.md
> +[![Community header](https://github.com/newrelic/opensource-website/raw/master/src/images/categories/Community_Project.png)](https://opensource.newrelic.com/oss-category/#community-project)
Thanks! I'll look into how to fix this in repo-linter 

https://github.com/newrelic/.github/blob/main/docs/repolinter/policy-overviews.md

2022-03-03 00:08 UTC, aswanson-nr reviewed
Looks good! I don't think we need the `generate-changelog` job unless that's also required

2022-03-03 00:08 UTC, aswanson-nr commented on .github/workflows/release.yml
> +              enforce_admins: true,
Unless this is required for the third party notices, we don't need to generate a changelog

2022-03-03 00:15 UTC, jpvajda commented on .github/workflows/release.yml
> +              enforce_admins: true,
I actually think a change log is just a good best practice for an OSS repository. So is there any reason not to include this functionality?

2022-03-03 17:15 UTC, aswanson-nr commented on .github/workflows/release.yml
> +            console.log("Result:", result)
```suggestion
      - name: Re-enable "required_pull_request_reviews" branch protection
        id: enable-branch-protection
        if: always()
        uses: actions/github-script@v1
        with:
          github-token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          previews: luke-cage-preview
          script: |
            const result = await github.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: null,
              restrictions: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                required_approving_review_count: 1
              }
            })
            console.log("Result:", result)
```

2022-03-03 17:19 UTC, jpvajda commented on .github/workflows/release.yml
> +            console.log("Result:", result)
@aswanson-nr is this any different? I'm seeing this error when trying to commit 

` Suggestion cannot be identical to original text.`

2022-03-03 17:20 UTC, aswanson-nr requested changes
Agreed on the changelog! Just need a few changes to the branch protection

2022-03-03 17:20 UTC, aswanson-nr commented on .github/workflows/release.yml
> +            console.log("Result:", result)
```suggestion
            const result = await github.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: false,
                contexts: [
                  'Gatsby Build Service - instant-observability-website'
                ]
              },
              restrictions: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                required_approving_review_count: 1
              }
            })
            console.log("Result:", result)
```

2022-03-03 17:20 UTC, aswanson-nr commented on .github/workflows/release.yml
> +              enforce_admins: true,
I can agree with that! Just two more comments then to get the branch protection right

2022-03-03 17:20 UTC, aswanson-nr commented on .github/workflows/release.yml
> +            console.log("Result:", result)
```suggestion
            const result = await github.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: false,
                contexts: [
                  'Gatsby Build Service - instant-observability-website'
                ]
              },
              restrictions: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                required_approving_review_count: 1
              }
            })
            console.log("Result:", result)
```

2022-03-03 17:22 UTC, aswanson-nr commented on .github/workflows/release.yml
> +            console.log("Result:", result)
Let me take a look

2022-03-03 17:24 UTC, aswanson-nr commented
Not sure what happened with those comments, but this is what needs to be added to the "re-enable branch protection"
```
required_status_checks: {
  strict: false,
  contexts: [
     'Gatsby Build Service - instant-observability-website'
  ]
},
```

2022-03-03 17:58 UTC, jpvajda commented
@aswanson-nr I made the suggested change, let me know what you think. Thanks for the input here!

2022-03-03 18:50 UTC, aswanson-nr commented on .github/workflows/release.yml
> +              required_status_checks: null,
You may need to do this locally, sometimes the formatting get's messed up with these suggestions
```suggestion
              required_status_checks: {
                strict: false,
                contexts: [
                    'Gatsby Build Service - instant-observability-website'
                ]
              },
```

2022-03-03 19:10 UTC, aswanson-nr approved these changes

2022-03-03 19:10 UTC, merged