chore:when we click on logo it has to open on same page
newrelic/instant-observability-website pull request #75
Opened 2022-03-10 11:39 UTC by sjyothi54

JIRA:https://newrelic.atlassian.net/browse/CXPUI-18
Description:In I/O Home page when we click on New Relic Logo it have to open  in same tab
@aswanson-nr / @jpvajda 
We changed externalLink component to anchor tag  because
if we add Changes to Link.js which is in this repo:https://github.com/newrelic/gatsby-theme-newrelic then changes will apply to the following sites's also
https://docs.newrelic.com/
https://developer.newrelic.com/
https://opensource.newrelic.com/

2022-03-10 17:10 UTC, josephgregoryii submitted a review, later dismissed

2022-03-10 21:51 UTC, aswanson-nr requested changes
Small comment about adding instrumentation!

2022-03-10 21:51 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +            <a
The only problem I can think of with using an `a` tag here instead of the `ExternalLink` component is that we'll lose out on some analytics that are built into the component. A quick fix for that would be to do what the `ExternalLink` component is doing and add a `useInstrumentedHandler` for the onClick event. [This](https://github.com/newrelic/gatsby-theme-newrelic/blob/7122abeea868758c89a0ca59b836f6af43b7d3e1/packages/gatsby-theme-newrelic/src/components/Link.js#L47-L53) is how the ExternalLink handles it, you'll just need to change the `origin` field

2022-03-14 15:49 UTC, sjyothi54 commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +            <a
@aswanson-nr I updated the changes
In order to work this merge this code
linked PR:https://github.com/newrelic/gatsby-theme-newrelic/pull/645 has to be merge first

2022-03-14 16:15 UTC, zstix submitted a review, later dismissed

2022-03-14 18:25 UTC, aswanson-nr reviewed
Hey @sjyothi54! I think some things may have just gotten lost in context on this PR. I don't think we want to make that update to the `ExternalLink` and `Link` components. Since it would only be used in this particular case. What you're trying to do can totally be done with the current tools available, the main thing is just keeping to tessen instrumentation for that link. I put together a quick example in #98, which should cover all the use cases for this link. If that meets all your requirements, feel free to pull that code over here or just merge that PR!

2022-03-15 07:31 UTC, sjyothi54 commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +            <a
@aswanson-nr Yes i made the changes

2022-03-15 15:52 UTC, aswanson-nr reviewed
Just needs a `href` attribute and it's good to go, I'll commit my suggested change and merge!

2022-03-15 15:52 UTC, aswanson-nr commented on src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
> +                origin: 'globalHeader',
```suggestion
                origin: 'globalHeader',
                href: 'https://newrelic.com',
```

2022-03-15 16:00 UTC, josephgregoryii approved these changes

2022-03-15 16:18 UTC, aswanson-nr approved these changes

2022-03-15 16:18 UTC, merged